export const ErrorCodes = {
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  EMAIL_ALREADY_EXISTS: 'EMAIL_ALREADY_EXISTS',
  EMAIL_NOT_VERIFIED: 'EMAIL_NOT_VERIFIED',
  ACCOUNT_SUSPENDED: 'ACCOUNT_SUSPENDED',
  INVALID_REFRESH_TOKEN: 'INVALID_REFRESH_TOKEN',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  NOT_FOUND: 'NOT_FOUND',
  CONFLICT: 'CONFLICT',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  GOOGLE_AUTH_FAILED: 'GOOGLE_AUTH_FAILED',
  INVALID_GOOGLE_TOKEN: 'INVALID_GOOGLE_TOKEN',
  PROVIDER_MISMATCH: 'PROVIDER_MISMATCH',
  GOOGLE_ACCOUNT_ALREADY_LINKED: 'GOOGLE_ACCOUNT_ALREADY_LINKED',
  GOOGLE_ACCOUNT_NOT_VERIFIED: 'GOOGLE_ACCOUNT_NOT_VERIFIED',
  INVALID_GOOGLE_IDENTITY: 'INVALID_GOOGLE_IDENTITY',
  ACCOUNT_DELETED: 'ACCOUNT_DELETED',
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];
