export const PROFESSIONAL_PROFILE_STATUS = {
  DRAFT: "DRAFT",
  PENDING_VERIFICATION: "PENDING_VERIFICATION",
  PUBLISHED: "PUBLISHED",
  UNPUBLISHED: "UNPUBLISHED",
} as const;

export type ProfessionalProfileStatus =
  (typeof PROFESSIONAL_PROFILE_STATUS)[keyof typeof PROFESSIONAL_PROFILE_STATUS];
